<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><Nullable>enable</Nullable><ImplicitUsings>disable</ImplicitUsings><PlatformTarget>x64</PlatformTarget><ApplicationManifest>../WindowOpacity/app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../WindowOpacity/WindowOpacity.csproj"/></ItemGroup></Project>
